#
###################################
# Site wide configuration
####################################
#
title:       "Leonids Jekyll theme"
description: "Clean Jekyll blog theme called Leonids."
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Africa/Lagos
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#https://www.smashingmagazine.com/2014/08/build-blog-jekyll-github-pages/
#
owner:
  name: Akinsete Sunday
  avatar: https://avatars0.githubusercontent.com/u/1130064?v=3&s=460
  job: "Mobile App Developer"
  bio: "Passionate about mobile app development"
  email:
  disqus-shortname:
  twitter:
  facebook:
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: akinmobile
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: sundayakinsete
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
